### ISSUE TITLE
Option to disable keyboard shortcut

### ISSUE THREAD

**Issue by wtflm** [xia-sava/parent-folder#3]
Would it be possible to disable or change the keyboard shortcut for Parent Folder? The default Alt+Up (or Option+Up on Mac) interferes with editing numeric CSS values in DevTools. Up/Down increases/decreases values in integer amounts (+-1), Ctrl/Cmd+Up/Down does it by tenfold (+-10) and Alt/Option+Up/Down does tenths (+-0.1). Every other combo works as expected on macOS, except for Option+Up when Parent Folder is enabled. It's actually very unfortunate as the DevTools style editor is often used to quickly prototype some styles that aren't saved anywhere yet and accidentally hitting Option+Up makes you navigate away and lose that context.

**Comment by xia-sava** [comment]
@wtflm can you try this?
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

> Up/Down increases/decreases values in integer amounts 

Wow, I've never seen this feature before. thx!

**Comment by wtflm** [comment]
> @wtflm can you try this? https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
> 
Looks like I learned something new as well. That is exactly what I needed, thank you.
